name: Release

on: create

jobs:
  release:
    name: Pypi
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    
    - name: Build and Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        RELEASE_VERSION: ${{ github.event.ref }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

    - name: Create Github Release
      uses: Roang-zero1/github-create-release-action@master
      with:
        created_tag: ${{ github.event.ref }}

    - name: Update Release with Artifacts
      uses: ncipollo/release-action@v1.6.1
      with:
        allowUpdates: true
        tag: ${{ github.event.ref }}
        artifacts: "dist/*"
        token: ${{ secrets.GITHUB_TOKEN }}